
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4NzUyNjY1","is_bot":false,"login":"ZhenyuYu1","name":"Zhenyu Yu"},"headRefName":"zy-UCSBDiningCommonsMenuItem-placeholders","number":79,"title":"zy - Added Menu Item placeholder pages for create, edit, index","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/79"},{"author":{"id":"MDQ6VXNlcjI2Njk2NTky","is_bot":false,"login":"SparklyJeff","name":"Jeffrey Cao"},"headRefName":"Jeffrey-CopyPlaceholder","number":72,"title":"Copy Help Request Tab from Placeholder","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/72"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"Chris-UCSBOrganization-Components","number":70,"title":"Add form and table components for UCSB organization, with tests.","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/70"}]
