
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"William-RecRequest-PlaceholderPages","number":97,"title":"WH - Copy Placeholders for RecommendationRequest pages","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/97"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"Chris-Organization-Edit","number":96,"title":"Chris - Add Organization Edit Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/96"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"Chris-Organization-Index","number":95,"title":"Chris - Add Organization Index Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/95"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"Chris-Organization-Create","number":94,"title":"Chris - Add Organization Create Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/94"},{"author":{"id":"MDQ6VXNlcjY4NzUyNjY1","is_bot":false,"login":"ZhenyuYu1","name":"Zhenyu Yu"},"headRefName":"zy-UCSBDiningCommonsMenuItem-edit","number":92,"title":"zy - Added edit page for Menu Item","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/92"},{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"William-RecRequest-Form","number":91,"title":"wh - implemented rec request form and tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/91"},{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"jc-MenuItemReview-index","number":89,"title":"Index Page for MenuItemReview plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/89"},{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"jc-MenuItemReview-page","number":88,"title":"Create Page for MenuItemReview plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/88"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"Chris-Organization-Table","number":86,"title":"Chris - Add Organization Table Component and Tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/86"}]
