
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-6pm-2
owner: ucsb-cs156-f23
repo_name: team03-f23-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5Mzc5NDY0","is_bot":false,"login":"justinchung712","name":""},"headRefName":"jc-MenuItemReview-edit","number":101,"title":"Edit Page for MenuItemReview plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/101"},{"author":{"id":"MDQ6VXNlcjcyODM5MjIz","is_bot":false,"login":"whuang602","name":"Will H."},"headRefName":"William-RecRequest-Table","number":99,"title":"wh - implemented rec request table and tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/99"},{"author":{"id":"U_kgDOBdHvcw","is_bot":false,"login":"vedantshah99","name":"Vedant Shah"},"headRefName":"Vedant-Articles-Components","number":98,"title":"Finished form and tables components","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/98"},{"author":{"id":"MDQ6VXNlcjg2NDkxMjg5","is_bot":false,"login":"cstraw2021","name":""},"headRefName":"Chris-Organization-Edit","number":96,"title":"Chris - Add Organization Edit Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-6pm-2/pull/96"}]
